@extends('layouts.defaultv2')

@section('title','Terms & Conditions |idoag.com')

@section('metatags')
    <meta name="keywords" content="Terms & Conditions |idoag.com" />
    <meta name="description" content="Terms & Conditions |idoag.com" />
@stop


@section('content')
    @include('layouts.headerv2')
    <div class="container">    
        <div id="accordion" class="myaccordion wow fadeInUp">
            <h1>{{$page->heading}}</h1>
            <div class="privacy_policy">
                <p>
                    The terms and conditions explain the nature and scope of the  relationship between Belobog Solutions that runs the website www.idoag.com  &amp; provides IDOAG Cards (as owner and management for the program) and who is  issued the IDOAG card. The terms and conditions cover limitations and  exclusions on the liability of Belobog Solutions, and the IDOAG partners. Usage  of this site is by affirming and stating that you have read, understood and  agree to all the following terms and conditions.</p>
                <ol type="1">
                    <li><strong>Definitions :</strong>&nbsp;In these  terms and conditions, unless the context specifies otherwise:
                        <p>1.1 Belobog  Solutions shall mean a company incorporated under the The Indian Partner Act,1932and having its  principal place of business at 04152, Tower-4, Ahinsa Khand-1, Indirapuram,  Ghaziabad, UP. and such expression shall, unless it be repugnant to the subject  or context thereof, include its successors, assigns, representatives and  transferees.</p><p>
                            1.2 The company  provides users with IDOAG Discount Card, various other opportunities or  benefits such as Internships, Seminars, guest Lectures, Events etc, a platform  for users to exhibit their creative passion while collaborating with other  users on the www.idoag.com, , Unless  explicitly stated otherwise, any new features that enhance the current service,  including the release of new features by the company, shall be subject to the  terms &amp; conditions. The Services are provided to the users through the  website www.idoag.com.</p><p>
                            1.3 “IDOAG  Member(s)” means a IDOAG customer, who is enrolled as a member of IDOAG holding  a valid IDOAG card/membership number. Membership to the program is governed by  these rules set by Belobog Solutions for this program which are subject to  change from time to time.</p><p>
                            1.4 “IDOAG  Network“ means all the IDOAG Partners including Brands and Institutions and  IDOAG for the time being taken as a whole.</p><p>
                            1.5 “IDOAG  Partner“ means any or all of the present or future entities, partners, shops,  departmental stores, restaurants, companies, institutions and other  participating establishments in the program whether with online or offline  presence, in agreement with Belobog Solutions, where members can get an access  to IDOAG services.</p></li>

                    <li><strong>General Conditions :</strong>
                        <p>2.1 The IDOAG  Member agrees that by using the IDOAG Card or by entering his/her IDOAG number  at www.idoag.com or at any IDOAG Partner online or offline, he/she is deemed to  have read and understood these terms and conditions and confirms that he/she is  bound by them and any changes that may comefrom time to time or such other  terms as specified from Belobog Solutions.</p><p>
                            2.2 Membership  into IDOAG Program is voluntary, open to all natural persons above the age of 17 with a correct  mailing address within India.</p><p>
                            2.3 Belobog  Solutions reserves the right to modify these Terms and Conditions and such  changes shall be deemed effective immediately upon posting of the modified  Terms and Conditions on www.idoag.com. Members’ continued holding of the IDOAG  Membership Account following the posting of changes on www.idoag.com will  indicate their acceptance of changes.</p><p>
                            2.4 The IDOAG  Discount card has certain validity as mentioned on the IDOAG cards issued to  its members. The membership and validity carries an annual fee as communicated  from time to time and would be communicated to the user upon loging into the  IDOAG account.</p><p>
                            2.5 IDOAG  Membership Account is not a payment medium or payment instrument.</p><p>
                            2.6 IDOAG Members  will be personally liable for any and all costs, taxes, charges, claims or  liabilities of whatever nature arising from the provision or availability of  benefits, facilities or arrangements provided or made available to a IDOAG  Member, by IDOAG Partners, as a result of his/her membership in the Program.</p><p>
                            2.7 Belobog  Solutions will endeavour to ensure that the services, benefits, facilities and  arrangements as expressed or advertised by the IDOAG Partners will be available  to the IDOAG Members. However, Belobog Solutions will not be liable for any  loss or damage, whether direct or indirect, arising from the provision or  non-provision whether whole or part, of any such services, benefits, facilities  or any other arrangements by the IDOAG Partners.</p><p>
                            2.8 When a IDOAG Member seeks to use  or obtain any of the services, benefits, facilities and arrangements as offered  by the IDOAG Partner, the provisions of such services, benefits, facilities or  arrangements will be subject to the respective terms and conditions of the  IDOAG Partner, being the provider of the said benefits, facilities and  arrangements.</p><p>
                            2.9 Belobog  Solutions shall not be liable for any loss or damage, whether direct or  indirect, resulting from termination or change of the Program or any of its  facilities, benefits or arrangements which are made available to the IDOAG  Members, including without limitation, IDOAG Partner's withdrawal or the withdrawal  or limiting of any such services, benefits or facilities.</p><p>
                            2.10 The Program  of IDOAG may be modified at the sole discretion of Belobog Solutions from time  to time without intimation to the IDOAG Member.</p><p>
                            2.11 Belobog  Solutions shall not be liable in the event it fails to fulfill any of its  obligations under this terms and conditions due to flood, earthquake, storm,  cyclone or any other acts of god of similar nature, war, strike, lockout, or  governmental or judicial or quasi-judicial policies/intervention/direction  /prohibition or change in law or for any other reasons beyond its control.</p><p>
                            2.12 A waiver of  any of the terms and conditions by Belobog Solutions shall not be deemed to be  a continuing waiver, but shall apply solely to the instances to which the  waiver is directed.</p><p>
                            2.13 An IDOAG  Card shall be accepted only at locations identified in the list provided to the  IDOAG Members at www.idoag.com. Belobog Solutions can at any time without  intimation to the IDOAG Members add and / or delete various Partners from such  list. The same shall be updated on www.idoag.com.</p><p>
                            2.14 IDOAG  Members are required to update all changes in the user contact detail to ‘IDOAG  Contact Center or at www.idoag.com. If a IDOAG Member fails to provide change  of address information immediately, IDOAG or its Partners will not be  responsible for any delay in delivery of the products/ services ordered by the  IDOAG Member.</p><p>
                            2.15 The IDOAG  Member acknowledges and understands that IDOAG is merely an intermediary and  does not assume any liability or acquire any right, title or interest in the  Rewards. IDOAG is only engaged in the management of the offers displayed on the  portal; however all the offers are in turn provided by the Vendors and Partners  to the Members directly.</p><p>
                            2.16 In order to  use the service, you must have access to the internet, either directly or  through devices that access web-based content. In addition, you must provide  all equipment necessary to make such connection to the internet, including a  computer and modem or other access device.</p><p>
                            2.17 IDOAG  Members understand and agree that the service is provided on "as is"  basis and that the company assumes no responsibility for the timeliness,  deletion, mis delivery or failure to store any user communications, pictures,  information or personalization settings.</p></li>

                    <li><strong>Access :</strong>
                        <p>We will provide  you with access to the Website in accordance with these Conditions.</p>

                    <strong>Your Obligations :
                        <p>3.1 You:</p></strong>
                        <p>
                            3.1.1 agree not to use the Website (or any part of) for any illegal purpose and  agree to use it in accordance with all relevant laws;</p><p>
                            3.1.2 agree not  to upload or transmit through the Website any computer viruses, macro viruses,  trojan horses, worms or anything else designed to interfere with, interrupt or  disrupt the normal operating procedures of a computer;</p><p>
                            3.1.3 will not  upload or transmit through the Website any material which is defamatory,  offensive, or of an obscene or menacing character, or that may cause annoyance,  inconvenience or needless anxiety;</p><p>
                            3.1.4 will not  use the Website in a way that may cause the Website to be interrupted, damaged,  rendered less efficient or such that the effectiveness or functionality of the  Website is in any way impaired;</p><p>
                            3.1.5 will not  use the Website in any manner which violates or infringes the rights of any  person, firm or company (including, but not limited to, rights of intellectual  property, rights of confidentiality or rights of privacy);</p><p>
                            3.1.6 will not  attempt any unauthorized access to any part or component of the Website or  create and publish a hypertext link to these unauthorized components; and</p><p>
                            3.1.7 agree that  in the event that you have any right, claim or action against any users arising  out of that user's use of the Website, then you will pursue such right, claim  or action independently of and without recourse to us.</p></li>

                    <li><strong>Indemnity :</strong>
                        <p>4.1 You agree to  be fully responsible for (and fully indemnify us against) all claims,  liability, damages, losses, costs and expenses, including legal fees, suffered  by us and arising out of any breach of the conditions by you or any other liabilities  arising out of your use of the website, or the use by any other person  accessing the website using your personal computer or internet access account.  You further agree that in the event of any action or claim brought against the  company due to or arising out of any content you submit, post to or transmit  through the service, your use of the service, your connection to the service,  your violation of the Terms and Conditions, or your violation of any rights of  another, you will reimburse the company for its reasonable attorneys' fees and  costs incurred in the defense of such action or claim.</p></li>

                    <li><strong>Our rights :</strong>
                        <p><strong>5.1 We reserve the right to:</strong></p><p>
                            5.1.1 modify or withdraw, temporarily or permanently, the website (or any part  of) with or without notice to you and you confirm that we shall not be liable  to you or any third party for any modification to or withdrawal of the Website;  and/or</p><p>
                            5.1.2 change  these conditions from time to time, and your continued use of the website (or  any part of) following such change shall be deemed to be your acceptance of  such change. It is your responsibility to check regularly to determine whether  the Conditions have been changed. If you do not agree to any change to the conditions  then you must immediately stop using the Website.</p><p>
                            5.2 We will use  our reasonable endeavors to maintain the website. The website is subject to  change from time to time. You will not be eligible for any compensation because  you cannot use any part of the Website or because of a failure, suspension or  withdrawal of all or part of the Website due to circumstances beyond our  control.</p></li>

                    <li><p><strong>Communication:</strong><strong> </strong>By agreeing to  the terms and condition stated herein, the <strong>users</strong> and the “<strong>IDOAG network</strong>” agree to  receive important communication related to offers, Password recovery, OTPs from  time to time using various modes of communications – Emails, Short Messaging  Services (SMS), Push notification from our portal or any other effective way of  communicating.</p>
                        <p>We reserve the  right to communicate with the Brands, Colleges and Users through SMS unless it  is requested upon. These SMS are in lieu with the DND norms of TRAI and shall  not be advertising SMSes but only an effective medium of communication to let  our network and users and colleges about new developments, offers and updates  to our website and IDOAG program.</p></li>

                    <li><strong>Third party links :</strong>
                        <p>In an attempt to  provide increased value to our Users, we may provide links to other websites or  resources. You acknowledge and agree that we are not responsible for the  availability of such external sites or resources, and do not endorse and are  not responsible or liable, directly or indirectly, for the privacy practices or  the content (including misrepresentative or defamatory content) of such  websites, including (without limitation) any advertising, products or other  materials or services on or available from such websites or resources, nor for  any damage, loss or offence caused or alleged to be caused by, or in connection  with, the use of or reliance on any such content, goods or services available  on such external sites or resources.</p></li>

                    <li><strong>Monitoring :</strong>
                        <p>We have the  right, but not the obligation, to monitor any activity and content associated  with the website. We may investigate any reported violation of these conditions  or complaints and take any action that we deem appropriate (which may include,  but is not limited to, issuing warnings, suspending, terminating or attaching  conditions to your access and/or removing any materials from the website).</p></li>

                    <li><strong>Intellectual property and right  to use :</strong>
                        <p>9.1 You  acknowledge and agree that all copyright, trademarks and all other intellectual  property rights in all material or content supplied as part of the Website  shall remain at all times vested in us or our licensors. You are permitted to  use this material only as expressly authorized by us.</p><p>
                            9.2 You  acknowledge and agree that the material and content contained within the website  is made available for your personal non-commercial use only and that you may  download such material and content onto only one computer hard drive for such  purpose. Any other use of the material and content of the website is strictly  prohibited. You agree not to (and agree not to assist or facilitate any third  party to) copy, reproduce, transmit, publish, display, distribute, commercially  exploit or create derivative works of such material and content.</p><p>
                            9.3 You hereby  agree that you do not (and do not allow any third party to) copy, modify,  create a derivative work of, reverse engineer, reverse assemble or otherwise  attempt to discover any source code, sell, assign, sublicense, grant a security  interest in or otherwise transfer any right in such software. You agree not to  modify the software in any manner or form, or to use modified versions of the  software, including (without limitation) for the purpose of obtaining  unauthorized access to the service. You also agree that the pictures and other  personal information of the other members are their proprietary material and  hence you would not misuse the same.</p></li>

                    <li><strong>Limitation of liability :</strong>
                        <p>10.1 While we  will use reasonable endeavors to verify the accuracy of any information we  place on the website, we make no warranties whether express or implied in  relation to its accuracy.</p><p>
                            10.2 The Website  is provided on an "as is" and "as available" basis without  any representation or endorsement. Unless specified in separate terms and  conditions related to a particular product or service, we make no warranties of  any kind, whether express or implied, in relation to the website, or products  or services offered on the website whether by us or on our behalf (including  free software downloads) including but not limited to, implied warranties of  satisfactory quality, fitness for a particular purpose, non-infringement,  compatibility, security, accuracy, condition or completeness, or any implied  warranty arising from course of dealing or usage or trade.</p><p>
                            10.3 Unless  specified in separate terms and conditions related to a particular product or  service, we make no warranty that the website or products or services offered  on the website whether by us or on our behalf (including free software  downloads) will meet your requirements or will be uninterrupted, timely, secure  or error-free, that defects will be corrected, or that the website or the  server that makes it available or products or services offered on the website whether  by us or on our behalf (including free software downloads) are free of viruses  or bugs or are fully functional, accurate, or reliable. We will not be  responsible or liable to you for any loss of content or material as a result of  uploading to or downloading from the website.</p><p>
                            10.4  Notwithstanding any other provision in the conditions, nothing shall limit your  rights as a consumer under law.</p><p>
                            10.5 You  acknowledge that we cannot guarantee and therefore shall not be in any way  responsible for the security or privacy of the website and any information  provided to or taken from the website by you.</p><p>
                            10.6 We will not  be liable in contract, tort or otherwise if you incur loss or damage connecting  to the website through a third party's hyper-text link.</p><p>
                            10.7 We will not  be liable, in contract, tort (including, without limitation, negligence),  pre-contract or other representations (other than fraudulent  misrepresentations) or otherwise out of or in connection with the website or  products or services offered on the website whether by us or on our behalf  (including free software downloads) for:</p><p>
                            10.7.1 any  economic losses (including without limitation loss of revenues, profits,  contracts, business or anticipated savings); or</p><p>
                            10.7.2 any loss  of goodwill or reputation; or</p><p>
                            10.7.3 any  special or indirect or consequential losses; in any case whether or not such  losses were within the contemplation of either of us at the date on which the  event giving rise to the loss occurred.</p><p>
                            10.8 Nothing in  the Conditions shall exclude or limit our liability for death or personal  injury resulting from our negligence or that of our servants, agents or  employees.</p></li>

                    <li><strong>Severance :</strong>
                        <p>If any part of  the Conditions shall be deemed unlawful, void or for any reason unenforceable,  then that provision shall be deemed to be severable from these conditions and  shall not affect the validity and enforceability of any of the remaining  provisions of the Conditions.</p></li>

                    <li><strong>Waiver :</strong>
                        <p>Nothing shall be  construed as a waiver by us of any preceding or succeeding breach of any  provision.</p></li>

                    <li><strong>Survival :</strong>
                        <p>Each provision of  these conditions shall be construed as separately applying and surviving even  if for any reason one or other of those provisions is held to be inapplicable  or unenforceable in any circumstances.</p></li>

                    <li><strong>Entire agreement :</strong>
                        <p>These conditions (as  amended from time to time) contain the entire agreement between you and us  relating to the subject matter covered and supersede any previous agreements,  arrangements, undertakings or proposals, written or oral, between you and us in  relation to such matters. No oral explanation or oral information given by  either of us shall alter the interpretation of these Conditions. You confirm  that, in agreeing to accept these conditions, you have not relied on any  representation save insofar as the same has expressly been made a  representation in these conditions and you agree that you shall have no remedy  in respect of any misrepresentation which has not become a term of these conditions  save that your agreement contained in this clause shall not apply in respect of  any fraudulent misrepresentation whether or not such has become a term of these  conditions.</p></li>

                    <li><strong>Miscellaneous information :</strong>
                        <p>The T&amp;Cs  constitute the entire agreement between you and Belobog Solutions and govern  your use of the service, superseding any prior agreements between you and  Belobog Solutions. You also may be subject to additional terms and conditions  that may apply when you use affiliate services, third-party content or third-party  software.</p><p>
                            You may from time  to time receive emails from the Belobog Solutions staff to enhance your  experience with this service; you may also receive emails to alert you to an  incomplete or possibly inaccurate profile or various offers and opportunities  that are either provided by Belobog Solutions or its partners. You may also  receive our partner commercial emails from us occasionally. You release company  from any liability arising from or related to such email transmissions to you.</p></li>

                    <li><strong>Content Posted on the Site :</strong>
                        <p>You understand  and hereby agree that all content including but not limited to information,  data, text, software, scripts, music, sound, photographs, graphics, video,  messages, tags, interactive features or other materials ("Content"),  whether publicly posted or privately transmitted, are the sole responsibility  of the person from whom such Content originated. This means that you and not  Belobog Solutions are entirely responsible for all Content that you upload,  post, mail, transmit or otherwise make available via the Service. Belobog  Solutions does not control the content posted via the service and, as such,  does not guarantee the accuracy, integrity or quality of such content. You  understand that by using the service, you may be exposed to content that is  offensive, indecent or objectionable. Under no circumstances will Belobog  Solutions be liable in any way for any content, including, but not limited to,  any errors or omissions in any content, or any loss or damage of any kind  incurred as a result of the use of any content posted, emailed, transmitted or  otherwise made available via the service. You understand and agree that Belobog  Solutions may delete any content that in the sole judgment of Belobog Solutions  violates any applicable law or this Agreement or which might be offensive,  illegal, defamatory, obscene, libelous, or that might violate the rights, harm,  or threaten the safety of other Belobog Solutions Members. Content is not  necessarily reviewed by Belobog Solutions prior to posting and does not  necessarily reflect the opinions or policies of Belobog Solutions. In addition,  Belobog Solutions will not and cannot censor or edit the content of any third-party  site.</p><p>
                            You are solely  responsible and liable for the Content that you publish or display  (hereinafter, "post") on the Site through the Belobog Solutions Service  (www.idoag.com), or transmit to other Belobog Solutions Members. Belobog  Solutions reserves the right to verify the authenticity of Content posted on  the Site. In exercising this right, Belobog Solutions may ask you to provide  any documentary or other form of evidence supporting your ownership or  otherwise of the content you post on the Site. If you fail to produce such  evidence, or if such evidence does not in the reasonable opinion of Belobog  Solutions establish or justify the claim, Belobog Solutions may, in its sole  discretion, remove the content from the site and terminate your membership without  a refund of your subscription fees.</p><p>
                            You acknowledge  that Belobog Solutions may or may not pre-screen content, but Belobog Solutions  and its designees shall have the right (but not the obligation) in their sole  discretion to pre-screen, refuse, or move any content that is available via the  service. Without limiting the foregoing, Belobog Solutions and its designees  shall have the right to remove any content that violates this Agreement or is  otherwise found objectionable. You agree that you must evaluate, and bear all  risks associated with, the use of any content, including any reliance on the  accuracy, completeness, or usefulness of such content. In this regard, you  acknowledge that you will not rely on any content created by Belobog Solutions  or submitted to Belobog Solutions, including without limitation information in  all pages or sections of Belobog Solutions.</p><p>
                            By posting content  to any public area of Belobog Solutions, you automatically grant, and you  represent and warrant that you have the right to grant, to Belobog Solutions,  and other Belobog Solutions members, an irrevocable, perpetual, non-exclusive,  royalty-free, worldwide license to use, copy, perform, display, and distribute  such information and Content and to prepare derivative works of, or incorporate  into other works, such information and Content, and to grant and authorize  sublicenses of the foregoing.</p><p>
                            With respect to  Content you submit or make available for inclusion on publicly accessible areas  of the Site, the license to use, distribute, reproduce, modify, adapt, publicly  perform and publicly display such content on the service solely for the  purposes of providing and promoting the specific property of the site to which  such content was submitted or made available. This license exists only for as  long as you elect to continue to include such content on the service and will  terminate at the time you remove or Belobog Solutions removes such content from  the service.</p><p>
                            With respect to content  that includes photos, graphics, audio or video you submit or make available for  inclusion on publicly accessible areas of the service the license to use,  distribute, reproduce, modify, adapt, publicly perform and publicly display  such content on the Service solely for the purpose for which such content was  submitted or made available. This license exists only for as long as you elect  to continue to include such content on the service and will terminate at the  time you remove or Belobog Solutions removes such content from the service.</p><p>
                            With respect to content  other than photos, graphics, audio or video you submit or make available for  inclusion on publicly accessible areas of the service the perpetual,  irrevocable and fully sub-licensable license to use, distribute, reproduce,  modify, adapt, publish, translate, publicly perform and publicly display such content  (in whole or in part) and to incorporate such content into other works in any  format or medium now known or later developed.</p><p>
                            "Publicly  accessible" areas of the Service are those areas of the Belobog Solutions  network of properties that are intended by Belobog Solutions to be available to  the general public. At the same time there may be other areas added on the site  from time to time.</p><p>
                            In connection with contents posted/submitted by you, you further  agree that you will not:</p>
                        <ul type="square"><li> submit material that is copyrighted, protected by trade secret or otherwise  subject to third party proprietary rights, including privacy and publicity  rights, unless you are the owner of such rights or have written permission from  their rightful owner to post the material and to grant Belobog Solutions all of  the license rights granted herein;</li>
                            <li>publish falsehoods or misrepresentations that could damage Belobog Solutions  or any third party;</li>
                            <li>impersonate another user.</li></ul>

                        <p> Belobog Solutions  does not endorse any User Content or any opinion, recommendation, or advice  expressed therein, and Belobog Solutions expressly disclaims any and all  liability in connection with Content submitted by the User. Belobog Solutions  does not permit copyright infringing activities and infringement of  intellectual property rights on its website, and Belobog Solutions will remove  all such infringing content if properly notified that such content or User  Submission infringes on another's intellectual property rights. Belobog  Solutions reserves the right to remove such content without prior notice.  Belobog Solutions will also terminate a User's access to its website, if they  are determined to be a repeat infringer. A repeat infringer (except in the case  of pornographic content) is a User who has been notified of infringing activity  more than twice and/or has had his/her Content removed from the website more  than twice.</p></li></ol>
                <p>   The  following is an inclusive list of the kind of Content that is illegal or  prohibited on the Site. Belobog Solutions will investigate and take appropriate  legal action in its sole discretion against anyone who violates this provision,  including without limitation, removing the offending communication/content from  the service and the site and terminating the membership of such violators  without a refund. It includes (but is not limited to) Content that:</p>

                <ol type="1" class="sub_ol">
                    <li>is patently offensive to any  community, such as Content that promotes racism, bigotry, hatred or physical  harm of any kind against any group or individual;</li>

                    <li>harasses or advocates harassment of  another person;</li>

                    <li>involves the transmission of  "junk mail", "chain letters," or unsolicited mass mailing  or "spamming";</li>
                    <li>for band and filmmaker profiles,  uses sexually suggestive imagery or any other unfair, misleading or deceptive  Content intended to draw traffic to the profile.</li>
                    <li>promotes information that the  person posting it is aware that it is false, misleading or promotes illegal  activities or conduct that is abusive, threatening, obscene, defamatory or  libelous;</li>
                    <li>promotes an illegal or unauthorized  copy of another person's copyrighted work, such as providing pirated computer  programs or links to them, providing information to circumvent  manufacture-installed copy-protect devices, or providing pirated music or links  to pirated music files;</li>
                    <li>contains restricted or password  only access pages, or hidden pages or images (those not linked to or from  another accessible page);</li>
                    <li>includes a photograph of another  person that you have posted without that person's consent; or</li>
                    <li>displays pornographic or sexually  explicit material of any kind;</li>
                    <li>criminal or tortures activity,  including child pornography, fraud, trafficking in obscene material, enticing  of minors, drug dealing, gambling, harassment, stalking, spamming, sending of  viruses or other harmful files, copyright infringement, patent infringement, or  theft of trade secrets;</li>
                    <li>provides material that exploits  people under the age of 18 years in a sexual or violent manner, or solicits  personal information from anyone under the age of 18 years;</li>
                    <li>furthers or promotes any criminal  activity or enterprise provides instructional information about illegal  activities such as making or buying illegal weapons, violating someone's  privacy, or providing or creating computer viruses;</li>
                    <li>covering or obscuring the banner  advertisements on your personal profile page, or any Belobog Solutions page via  HTML/CSS or any other means;</li>
                    <li>attempting to impersonate another member  or person;</li>
                    <li>solicits passwords or personal  identifying information for commercial or unlawful purposes from other users/members;  and</li>
                    <li>engages in commercial activities  and/or sales such as contests, sweepstakes, barter, advertising, and pyramid  schemes.</li>
                    <li>displaying an advertisement on your  profile, or accepting payment or anything of value from a third person in  exchange for your performing any commercial activity on or through the Belobog  Solutions Website on behalf of that person, such as placing commercial content  on your profile, posting blogs or bulletins with a commercial purpose,  selecting a profile with a commercial purpose, or sending private messages with  a commercial purpose; or</li>
                    <li>for band profiles, copying your  Belobog Solutions code and embedding it into other profiles or asking other members  to embed it into their profiles;</li>
                    <li>encourages, invites or solicits  extra marital affairs.</li>
                    <li>using the Belobog Solutions website  in a manner inconsistent with any and all applicable laws and regulations.</li>
                </ol>

                <p>You must use the  Belobog Solutions Service in a manner consistent with any and all applicable  local and state, and federal laws rules and regulations.</p><p>
                    You must not  include in your member profile, any telephone numbers, street addresses, last  names, URL's, and email addresses that are either patently visible to the other  members or can be deciphered or deduced. When creating your account, you must  provide accurate and complete information. You are solely responsible for the  activity that occurs on your account, and you must keep your account password  secure.</p><p>
                    You are not  permitted to create multiple profiles. If Belobog Solutions becomes aware that  you have created multiple profiles or have provided false information in order  to secure access to the website, your membership is liable to be terminated  forthwith without any refund of subscription fees.</p><p>
                    If at any time  Belobog Solutions is of the view in its sole discretion that your profile  contains any information or material or Content which is objectionable,  unlawful or illegal, Belobog Solutions has the right in its sole discretion to  forthwith terminate your membership without refund of your subscription fees  and delete such objectionable, illegal or unlawful information, material or  Content from your profile and disallow you to continue as a Member.</p><p>
                    In consideration  of your use of the Site and Services, you agree, where information is requested,  to provide true, accurate, current, and complete information about yourself,  and to maintain and update it promptly. You agree that if any information you  provide is false, inaccurate, not current, or incomplete, we may terminate your  use of the Site and/or the Services.</p>
            </div>
        </div>
    </div>
    @include('layouts.footerv2')
    <!-- Footer Ends here -->

@stop